function renderCustomers(){
 let t=document.getElementById('customerTable');if(!t)return;
 let rows=[...(data.customers||[])].sort((a,b)=>a.lastName.localeCompare(b.lastName)||a.firstName.localeCompare(b.firstName));
 let canEdit=hasRolePermission('treatment_booking_settings','edit');
 t.innerHTML="<tr><th>Account</th><th>Name</th><th>DOB</th><th>Phone</th><th>Minutes Left</th><th>ID Checked</th><th></th></tr>"+(rows.length?rows.map(c=>`<tr class='clinicRow' onclick="openCustomer('${c.id}')"><td>${escapeHtml(c.accountNumber)}</td><td><b>${escapeHtml(c.firstName)} ${escapeHtml(c.lastName)}</b></td><td>${formatSunbedDisplayDate(c.dob)}</td><td>${escapeHtml(c.phone||'')}</td><td><b>${c.minutesLeft}</b></td><td>${c.idChecked?'Yes':'No'}</td><td>${canEdit?`<button onclick="event.stopPropagation();deleteCustomer('${c.id}')">Delete</button>`:''}</td></tr>`).join(''):"<tr><td colspan='7' class='muted'>No customers yet.</td></tr>");
 let sel=document.getElementById('sessionCustomer');if(sel){let v=sel.value;sel.innerHTML="<option value=''>Select customer...</option>"+rows.map(c=>`<option value='${c.id}'>${escapeHtml(c.firstName)} ${escapeHtml(c.lastName)} · ${escapeHtml(c.accountNumber)}</option>`).join('');sel.value=v}
}
async function deleteCustomer(id){
 let c=data.customers.find(x=>x.id===id);if(!c)return;
 if(!confirm(`Delete customer ${c.firstName} ${c.lastName}?`))return;
 let {error}=await sb.from('customers').delete().eq('id',id);
 if(error){alert('This customer cannot be deleted because they have linked session or payment history. Remove test history first, or keep the customer for the audit trail.\n\n'+error.message);return}
 await loadLiveData();renderCustomers();
}
function openCustomerCreate(){editingCustomerId=null;document.getElementById('customerModalTitle').textContent='New Customer';document.getElementById('customerAccountLabel').textContent='Account number will be generated automatically.';['custFirst','custLast','custDob','custPhone','custAddress'].forEach(id=>document.getElementById(id).value='');document.getElementById('custUv').value='true';document.getElementById('custIdChecked').value='false';document.getElementById('custIdDate').value='';document.getElementById('custMinutes').value='0';document.getElementById('customerPurchaseArea').style.display='none';document.getElementById('customerError').style.display='none';document.getElementById('customerModal').classList.add('show')}
function openCustomer(id){let c=data.customers.find(x=>x.id===id);if(!c)return;editingCustomerId=id;document.getElementById('customerModalTitle').textContent=`${c.firstName} ${c.lastName}`;document.getElementById('customerAccountLabel').textContent=`Account ${c.accountNumber}`;document.getElementById('custFirst').value=c.firstName;document.getElementById('custLast').value=c.lastName;document.getElementById('custDob').value=c.dob;document.getElementById('custPhone').value=c.phone||'';document.getElementById('custAddress').value=c.address||'';document.getElementById('custUv').value=String(c.uv);document.getElementById('custIdChecked').value=String(c.idChecked);document.getElementById('custIdDate').value=c.idCheckedDate||'';document.getElementById('custMinutes').value=c.minutesLeft;document.getElementById('customerPurchaseArea').style.display='block';renderCustomerPurchases(c);document.getElementById('customerModal').classList.add('show')}
function closeCustomerModal(){document.getElementById('customerModal').classList.remove('show')}
async function saveCustomer(){
 let first=document.getElementById('custFirst').value.trim(),last=document.getElementById('custLast').value.trim(),dob=document.getElementById('custDob').value,phone=document.getElementById('custPhone').value.trim(),address=document.getElementById('custAddress').value.trim(),uv=document.getElementById('custUv').value==='true',idChecked=document.getElementById('custIdChecked').value==='true',age=ageFromDob(dob),err=document.getElementById('customerError');err.style.display='none';
 if(!first||!last||!dob){err.textContent='First name, last name and DOB are required.';err.style.display='block';return}
 if(age<18){alert('CUSTOMER IS BELOW 18 AND CAN NOT BE A CUSTOMER.');return}
 let duplicate=(data.customers||[]).find(c=>c.id!==editingCustomerId&&c.dob===dob&&c.firstName.trim().toLowerCase()===first.toLowerCase()&&c.lastName.trim().toLowerCase()===last.toLowerCase());
 if(duplicate){err.textContent=`A customer with the name ${first} ${last} and this date of birth already exists (${duplicate.accountNumber}).`;err.style.display='block';return}
 if(uv&&age<25&&!idChecked)alert('CHECK CUSTOMER ID');
 let payload={first_name:first,last_name:last,date_of_birth:dob,phone_number:phone||null,address:address||null,intends_uv_or_injectables:uv,id_checked:idChecked,updated_at:new Date().toISOString()},error,row;
 if(editingCustomerId)({data:row,error}=await sb.from('customers').update(payload).eq('id',editingCustomerId).select().single());else({data:row,error}=await sb.from('customers').insert(payload).select().single());
 if(error){
   err.textContent=error.code==='23505'
     ?'A customer with this name and date of birth already exists.'
     :error.message;
   err.style.display='block';return
 }
 await loadLiveData();renderCustomers();openCustomer(row.id)
}
function renderCustomerPurchases(c){
 let products=(data.tanningProducts||[]).filter(p=>p.active&&p.type==='Block Minutes').sort((a,b)=>a.minutes-b.minutes);
 document.getElementById('blockPurchaseButtons').innerHTML=products.map(p=>`<button class='purchaseMinuteBtn' onclick="openBlockPurchase('${p.id}')">${p.minutes} Minutes<br><span class='muted'>£${p.price.toFixed(2)}</span></button>`).join('')||"<div class='muted'>No Block Minutes products configured.</div>";
 let tx=(data.customerTransactions||[]).filter(x=>x.customerId===c.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
 document.getElementById('customerTransactionTable').innerHTML="<tr><th>Date</th><th>Type</th><th>Details</th><th>Value</th><th>Minutes</th><th>Balance</th></tr>"+(tx.length?tx.map(x=>`<tr><td>${new Date(x.createdAt).toLocaleString('en-GB')}</td><td>${x.type}</td><td>${x.product||''}</td><td>£${x.value.toFixed(2)}</td><td>${x.minutes>0?'+':''}${x.minutes}</td><td>${x.balance}</td></tr>`).join(''):"<tr><td colspan='6' class='muted'>No transactions yet.</td></tr>")
}
function openBlockPurchase(id){purchaseProductId=id;document.getElementById('purchaseQty').value='1';updatePurchaseSummary();document.getElementById('purchaseModal').classList.add('show')}
function updatePurchaseSummary(){let p=data.tanningProducts.find(x=>x.id===purchaseProductId),q=Math.max(1,+document.getElementById('purchaseQty').value||1);if(p)document.getElementById('purchaseSummary').textContent=`Purchasing ${q} × ${p.title} (${p.minutes*q} minutes) for £${(p.price*q).toFixed(2)}.`}
async function completeBlockPurchase(){let q=Math.max(1,+document.getElementById('purchaseQty').value||1),{data:bal,error}=await sb.rpc('purchase_block_minutes',{p_customer:editingCustomerId,p_product:purchaseProductId,p_quantity:q});if(error)return alert(error.message);document.getElementById('purchaseModal').classList.remove('show');await loadLiveData();openCustomer(editingCustomerId);alert(`Purchase complete. ${bal} minutes left on account.`)}
function renderTanningProducts(){let t=document.getElementById('tanningProductsTable');if(!t)return;let rows=data.tanningProducts||[];t.innerHTML="<tr><th>Type</th><th>Product</th><th>Minutes</th><th>Price</th><th>Stock</th></tr>"+rows.map(p=>`<tr class='clinicRow' onclick="openTanningProduct('${p.id}')"><td>${escapeHtml(p.type)}</td><td><b>${escapeHtml(p.title)}</b></td><td>${p.minutes??'—'}</td><td>£${p.price.toFixed(2)}</td><td>${p.stock??'—'}</td></tr>`).join('')}
function openTanningProduct(id=null){editingTanningProductId=id;let p=id?data.tanningProducts.find(x=>x.id===id):null;document.getElementById('tanningProductTitle').textContent=p?'Edit Product':'New Product';let types=['PAYG Minutes','Block Minutes','RLT Programme','Tangible'],selected=p?.type||'PAYG Minutes';document.getElementById('productTypeButtons').innerHTML=types.map(x=>`<button type='button' class='${x===selected?'primary':''}' onclick="selectTanningProductType('${x}')">${x}</button>`).join('');document.getElementById('tanningProductModal').dataset.type=selected;document.getElementById('tpTitle').value=p?.title||'';document.getElementById('tpPrice').value=p?.price??'';document.getElementById('tpMinutes').value=p?.minutes??'';document.getElementById('tpStock').value=p?.stock??'';document.getElementById('tpDescription').value=p?.description||'';updateTanningProductFields();document.getElementById('deleteTanningProductBtn').style.display=p?'inline-block':'none';document.getElementById('tanningProductModal').classList.add('show')}
async function deleteTanningProduct(){if(!editingTanningProductId)return alert('Save the product before it can be deleted.');if(!confirm('Delete this product?'))return;let {error}=await sb.from('tanning_rlt_products').delete().eq('id',editingTanningProductId);if(error)return alert(error.message);document.getElementById('tanningProductModal').classList.remove('show');await loadLiveData();renderTanningProducts()}
function selectTanningProductType(t){let modal=document.getElementById('tanningProductModal');modal.dataset.type=t;document.getElementById('productTypeButtons').querySelectorAll('button').forEach(b=>b.classList.toggle('primary',b.textContent===t));updateTanningProductFields()}
function updateTanningProductFields(){let t=document.getElementById('tanningProductModal').dataset.type;document.getElementById('tpMinutesWrap').style.display=['PAYG Minutes','Block Minutes'].includes(t)?'block':'none';document.getElementById('tpStockWrap').style.display=t==='Tangible'?'block':'none'}
async function saveTanningProduct(){let type=document.getElementById('tanningProductModal').dataset.type,title=document.getElementById('tpTitle').value.trim(),price=+document.getElementById('tpPrice').value,minutes=+document.getElementById('tpMinutes').value||null,stock=+document.getElementById('tpStock').value||null,description=document.getElementById('tpDescription').value.trim();if(!title||!Number.isFinite(price))return alert('Enter a title and valid price.');let payload={product_type:type,title,description:description||null,minute_amount:['PAYG Minutes','Block Minutes'].includes(type)?minutes:null,price,current_stock_level:type==='Tangible'?stock:null,updated_at:new Date().toISOString()},error;if(editingTanningProductId)({error}=await sb.from('tanning_rlt_products').update(payload).eq('id',editingTanningProductId));else({error}=await sb.from('tanning_rlt_products').insert(payload));if(error)return alert(error.message);document.getElementById('tanningProductModal').classList.remove('show');await loadLiveData();renderTanningProducts()}
function sessionCustomerChanged(){let c=data.customers.find(x=>x.id===document.getElementById('sessionCustomer').value);document.getElementById('sessionCustomerBalance').textContent=c?`${c.minutesLeft} minutes left on account.`:'Select a customer to see account minutes.'}
function purchaseMoreFromSession(){let id=document.getElementById('sessionCustomer').value;document.getElementById('insufficientMinutesModal').classList.remove('show');if(id)openCustomer(id)}
function buyPaygRemainder(){let c=data.customers.find(x=>x.id===document.getElementById('sessionCustomer').value),len=+document.getElementById('sessionLength').value;if(!c)return;let use=confirm(`Use the customer's remaining ${c.minutesLeft} account minutes and pay for the remaining ${Math.max(0,len-c.minutesLeft)} minutes?`);if(use){pendingPaygSplit={account:Math.min(c.minutesLeft,len),payg:Math.max(0,len-c.minutesLeft)};let pp=data.tanningProducts.find(p=>p.active&&p.type==='PAYG Minutes'&&p.minutes===pendingPaygSplit.payg),priceText=pp?` (£${pp.price.toFixed(2)})`:'';document.getElementById('sessionPayment').value='PAYG - Card';document.getElementById('insufficientMinutesModal').classList.remove('show');alert(`${pendingPaygSplit.payg} minutes${priceText} need to be paid for. Complete payment, then press Record Session.`)}}
